/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asper.bank;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;

/**
 *
 * @author remix_alpha
 */
public class Registrationthree extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Registrationthree
     */
    public Registrationthree() {
        initComponents();
         setLocation(350, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        accountType = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Applicationlabal = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1092, 668));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(25, 24, 37));
        jLabel15.setFont(new java.awt.Font("Abyssinica SIL", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(25, 24, 37));
        jLabel15.setText("ASPER BANK");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asper/bank/images/small_logo-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asper/bank/images/Untitled design (14).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 70, 470, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accountType.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        accountType.setText("Account Type");
        jPanel3.add(accountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel5.setText("Card Number");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel6.setText("PIN");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel8.setText("Services Required");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, 30));

        Applicationlabal.setFont(new java.awt.Font("Mukti Narrow", 1, 18)); // NOI18N
        Applicationlabal.setText("Page 3 : Account Details");
        jPanel3.add(Applicationlabal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        Back.setForeground(new java.awt.Color(46, 138, 243));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asper/bank/images/Untitled design (5).png"))); // NOI18N
        Back.setAlignmentX(5.0F);
        Back.setAlignmentY(5.0F);
        Back.setBorder(null);
        Back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Back.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        Back.setMargin(new java.awt.Insets(5, 14, 5, 14));
        Back.setPreferredSize(new java.awt.Dimension(50, 50));
        Back.setVerifyInputWhenFocusTarget(false);
        Back.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel3.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 42, 97));

        r1.setBackground(new java.awt.Color(255, 255, 255));
        r1.setText("Saving Account");
        jPanel3.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        r2.setBackground(new java.awt.Color(255, 255, 255));
        r2.setText("Fixed Deposit Account");
        jPanel3.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        r4.setBackground(new java.awt.Color(255, 255, 255));
        r4.setText("Recurring Deposit Account");
        jPanel3.add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        r3.setBackground(new java.awt.Color(255, 255, 255));
        r3.setText("Current Account");
        jPanel3.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jTextField1.setText("XXXX-XXXX-XXXX-4184");
        jTextField1.setBorder(null);
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 170, -1));

        jTextField2.setText("XXXX");
        jTextField2.setBorder(null);
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setText("ATM CARD");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel3.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setText("Online Banking");
        jPanel3.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        c3.setBackground(new java.awt.Color(255, 255, 255));
        c3.setText("Mobile Banking");
        jPanel3.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        c4.setBackground(new java.awt.Color(255, 255, 255));
        c4.setText("Email & SMS Alorts");
        jPanel3.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, -1));

        c5.setBackground(new java.awt.Color(255, 255, 255));
        c5.setText("Cheque Book");
        jPanel3.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, -1, 30));

        c6.setBackground(new java.awt.Color(255, 255, 255));
        c6.setText("E-Statement");
        jPanel3.add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, 30));

        submit.setBackground(new java.awt.Color(105, 51, 151));
        submit.setFont(new java.awt.Font("aakar", 1, 15)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel3.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, 90, 30));

        cancel.setBackground(new java.awt.Color(40, 66, 245));
        cancel.setFont(new java.awt.Font("aakar", 1, 15)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel3.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 90, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -30, 730, 660));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asper/bank/images/regisbackground.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(1270, 675));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        
        cancel.addActionListener(this);
          setVisible(false);
          new Sidehome().setVisible(true);


    }//GEN-LAST:event_cancelActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Registrationtwo().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        submit.addActionListener(this);
    }//GEN-LAST:event_submitActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    
    public void actionPerformed(ActionEvent ae){
        
        if(ae.getSource() == submit){
         
            String accountType = null;
            if(r1.isSelected()){
                accountType = "Saving Account";
            }else if(r2.isSelected()){
                accountType = "Fixed Deposit Account";
            } else if(r3.isSelected()){
                accountType = "Current Account";
            }  if(r4.isSelected()){
                accountType = "Reccuring Deposit Account";
            }
            
            
            Random random = new Random();
            String cardnumber = "" + Math.abs((random.nextLong() % 90000000L)) + 5040936000000000L;
            String pinnumber = "" + Math.abs((random.nextLong() % 9000L) + 1000L);
            
            String facility = "";
            if(c1.isSelected()){
                facility = facility + "ATM CARD";
            }else if(c2.isSelected()){
                facility = facility + "Online Banking";
            }else if(c3.isSelected()){
                facility = facility + "Mobile Banking";
            }else if(c4.isSelected()){
                facility = facility + "Email & SMS Alerts";
            }else if(c5.isSelected()){
                facility = facility + "Cheque Book";
            }else if(c6.isSelected()){
                facility = facility + "Statement";
            }   
            
            try{
                if(accountType.equals("")){
                    JOptionPane.showMessageDialog(null,"Account Type is Required");
                }else{
                    conn c = new conn();
                    String queryl = "insert into accdetails values('"+accountType+"','"+cardnumber+"','"+pinnumber+"','"+facility+"')";
                    String query2 = "insert into login values('"+cardnumber+"','"+pinnumber+"')";
                    c.s.executeUpdate(queryl);
                    JOptionPane.showMessageDialog(null,"Registration succesfull");
                    JOptionPane.showMessageDialog(null,"CARD NUMBER :" + cardnumber +"\n PIN ; " + pinnumber);
                }
            }catch(Exception e){
                 System.out.println(e);
            }
            
            
        }else if(ae.getSource() == cancel){
            
            
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrationthree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrationthree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrationthree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrationthree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     
                new Registrationthree().setVisible(true);;
                       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Applicationlabal;
    private javax.swing.JButton Back;
    private javax.swing.JLabel accountType;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
